### ISSUE TITLE
Improve `crosslink`

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-go-build-tools#146] opened 2022-10-04 16:30 UTC
So that it makes better decisions when adding replace statements (see https://github.com/open-telemetry/opentelemetry-collector/pull/6199#discussion_r986303623)

**Comment by bryan-aguilar** [comment] 2022-10-05 02:23
Without more information I will say that crosslink does not blindly insert replace statements. The old version of crosslink that the `otel-go` repositories used did that. The new crosslink adds only the necessary direct and transitive intra-repository dependencies.

**Comment by bogdandrutu** [comment] 2022-10-05 05:38
@bryan-aguilar nice, lets see this in practice, thanks :)

**Comment by codeboten** [comment] 2023-06-14 19:02
Re-opening this issue, `make crosslink` in the collector core repo adds replace statements even when there are no direct dependencies on modules. See https://github.com/open-telemetry/opentelemetry-collector/pull/7883#discussion_r1230031489

**Comment by bryan-aguilar** [comment] 2023-06-14 19:05
Please assign this to me. I'll take a look into it.

**Comment by codeboten** [comment] 2023-06-14 19:55
Thanks @bryan-aguilar!

**Comment by bryan-aguilar** [comment] 2023-06-14 20:59
> Re-opening this issue, `make crosslink` in the collector core repo adds replace statements even when there are no direct dependencies on modules. See [open-telemetry/opentelemetry-collector#7883 (comment)](https://github.com/open-telemetry/opentelemetry-collector/pull/7883#discussion_r1230031489)

The reason that this is happening in this instance is that the ballast extension [takes a requirement](https://github.com/open-telemetry/opentelemetry-collector/blob/05d57d966f2afe7cc139cdac87e2c768c2a125b5/extension/ballastextension/go.mod#L7) on `go.opentelemetry.io/collector` which is an intra repository depdendency. Crosslink builds a graph of intra repository dependencies and ensures all packages have replace statements inserted. [Here](https://github.com/open-telemetry/opentelemetry-collector/blob/05d57d966f2afe7cc139cdac87e2c768c2a125b5/go.mod#L25) is where that intra repository dependency for the `auth` package is introduced in `go.opentelemetry.io/collector`. This process continues for the entire graph. This is a feature and not a bug. The ensure that all direct and transitive dependencies for intra repository dependencies have replace statements inserted. 

cc: @codeboten @jpkrohling

**Comment by pellared** [comment] 2023-06-20 10:59
> The ensure that all direct and transitive dependencies for intra repository dependencies have replace statements inserted.

I totally agree that it is as expected. Closing.

**Closed by pellared** 2023-06-20 10:59 UTC
